require 'simple_warehouse/commands/help'
require 'simple_warehouse/commands/init'
require 'simple_warehouse/commands/store'
require 'simple_warehouse/commands/locate'
require 'simple_warehouse/commands/remove'
require 'simple_warehouse/commands/view'
require 'simple_warehouse/commands/exit'
